CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(50) UNIQUE KEY,
    password VARCHAR(60)
);
CREATE TABLE todo (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    owner INTEGER,
    text VARCHAR(255),
    done BOOLEAN DEFAULT FALSE
);